### ISSUE TITLE
Publish on the Chrome Web Store

### ISSUE THREAD

**Issue by hferreiro** [song-fangzhen/chromium-open-ide#2]

**Comment by song-fangzhen** [comment]
Hi, hferreiro. Glad to hear you like it!
I don’t have a Visa card to register as a google extension developer, that’t the reason I didn’t upload COI to chrome web store at the first time.

But don’t worry, my card is on the way. And l’m sure COI will appear on chrome web store soon or later. I’ll comeback when it’s done. :)
